setup CI/CD
BakingUp/BakingUp-Backend pull request #1
Opened 2024-08-24 14:48 UTC by KNattawat89

2024-08-24 15:16 UTC, jedipw requested changes

2024-08-24 15:16 UTC, jedipw commented on .github/workflows/ci.yml
> +    - '*'
คิดว่าไม่ควร deploy ลง server ทุกครั้งที่ pull request จาก branch ไหนก็ได้ ควร deploy แค่ตอน push ลง main อย่างเดียว
ส่วน build and test อันนี้คิดว่าน่าจะโอเคแล้วที่ขึ้นตอน pull request จาก branch ไหนก็ได้

2024-08-24 16:43 UTC, bbbung approved these changes

2024-08-25 01:26 UTC, jedipw approved these changes

2024-08-25 01:27 UTC, merged